### ISSUE TITLE
Just a little review

### ISSUE THREAD

**Issue by kylepaulsen** [BenjaminVerble/mini-view#1]
I don't think there is a need to cache anything because the interpolate function just returns a string. You wouldn't want to cache the fully interpolated strings anyway. So this line is not needed:
https://github.com/BenjaminVerble/mini-view/blob/7c66a6f78e4633e776290995f194ebbabb51ac95/index.js#L75

Also you can just call the function normally so no need to use bind:
https://github.com/BenjaminVerble/mini-view/blob/7c66a6f78e4633e776290995f194ebbabb51ac95/index.js#L59

This will also reduce your memory footprint.

**Comment by BenjaminVerble** [comment]
thanks kyle

**Comment by BenjaminVerble** [comment]
removed caching b/c I don't see myself or others using text/template script tags. also, this could be handled separately.
